# Nombre del paquete
package_name: EPA-ModeloLectura

# Archivos de datos
# data_file: EXA_2022_1_Todos_Limp.csv
train_data_file: EPA-ModeloLectura-train.csv
test_data_file: EPA-ModeloLectura-test.csv

# Variables
# Objetivo
target: EXA_C_RTAS_CORR_LC

features:
  - ESTU_GRADO
  - COLE_COD_ICFES
  - COLE_COD_MCPIO
  - COLE_COD_DPTO
  - EXA_C_RTAS_CORR_CN
  - EXA_C_RTAS_CORR_CC
  - EXA_C_RTAS_CORR_MT
  - ESTU_GENERO_F
  - COLE_NATURALEZA_O
  - COLE_JORNADA_COMPLETA
  - COLE_JORNADA_MAÑANA
  - COLE_JORNADA_TARDE
  - EXA_MODALIDAD_OFF
  - EXA_MODALIDAD_ON
  - EXA_MODALIDAD_PA

temp_features:
  - EXA_N_RTAS_CORR_LC
  
# pipelines
pipeline_name: EPA-ModeloLectura
pipeline_save_file: EPA-ModeloLectura-output

# fracción del conjunto de prueba
test_size: 0.33

# semilla
random_state: 42

# Hiperparámetros del modelo 
n_estimators: 200
learning_rate: 0.2
max_depth: 5

# variables a mapear
qual_vars:
  - EXA_C_RTAS_CORR_LC

# Variables categóricas
categorical_vars:
  - ESTU_GENERO_F
  - COLE_NATURALEZA_O
  - COLE_JORNADA_COMPLETA
  - COLE_JORNADA_MAÑANA
  - COLE_JORNADA_TARDE
  - EXA_MODALIDAD_OFF
  - EXA_MODALIDAD_ON
  - EXA_MODALIDAD_PA

# Mapeo de variables 
qual_mappings:
  Low reading skills: 0
  Mid reading skills: 1
  High reading skills: 2
