# Nombre del paquete
package_name: EPA-ModeloLectura

# Archivos de datos
# data_file: EXA_2022_1_Todos_Limp.csv
train_data_file: EPA-ModeloLectura-train.csv
test_data_file: EPA-ModeloLectura-test.csv

# Variables
# Objetivo
target: EXA_N_RTAS_CORR_LC

features:
  - ESTU_GRADO
  - COLE_COD_ICFES
  - COLE_COD_MCPIO
  - COLE_COD_DPTO
  - EXA_N_RTAS_CORR_CN
  - EXA_N_RTAS_CORR_CC
  - EXA_N_RTAS_CORR_MT  

temp_features:
  - EXA_N_RTAS_CORR_LC
  
# pipelines
pipeline_name: EPA-ModeloLectura
pipeline_save_file: EPA-ModeloLectura-output

# fracción del conjunto de prueba
test_size: 0.33

# semilla
random_state: 42

# TODO: hiperparámetros del modelo 
n_estimators: 850
max_depth: 19

# variables a mapear
qual_vars:
  - EXA_N_RTAS_CORR_LC

# TODO: Pendiente
categorical_vars:
  - EXA_N_RTAS_CORR_LC

# TODO: mapeo de variables 
qual_mappings:
  Attrited Customer: 1
  Existing Customer: 0
