# Nombre del paquete
package_name: ModeloEducarParaAvanzar

# Archivos de datos
train_data_file: EducarParaAvanzar_train.csv
test_data_file: EducarParaAvanzar_test.csv

# Variables
# Objetivo
target: EXA_N_RTAS_CORR_LC

features:
  - ESTU_CONSECUTIVO
  - ESTU_GRADO
  - ESTU_GENERO
  - COLE_COD_ICFES
  - COLE_NATURALEZA
  - COLE_CALENDARIO
  - COLE_JORNADA
  - COLE_COD_MCPIO
  - COLE_NOM_MCPIO
  - COLE_COD_DPTO
  - COLE_NOM_DPTO
  - EXA_MODALIDAD
  - EXA_N_RTAS_CORR_CN
  - EXA_N_RTAS_CORR_CC
  - EXA_N_RTAS_CORR_MT

temp_features:
 - COLE_NOM_ESTABLECIMIENTO

# pipelines
pipeline_name: ModeloEducarParaAvanzar
pipeline_save_file: ModeloEducarParaAvanzar_output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperparámetros del modelo 
n_estimators: 850
max_depth: 19

# # variables a mapear
# qual_vars:
#   - EXA_N_RTAS_CORR_LC

# Variables categóricas
categorical_vars:
  - ESTU_GRADO
  - ESTU_GENERO
  - COLE_NATURALEZA
  - COLE_CALENDARIO
  - COLE_JORNADA
  - EXA_MODALIDAD

# # mapeo de variables
# qual_mappings:
#   Attrited Customer: 1
#   Existing Customer: 0